### PR TITLE
Compatibility overhaul

### PR DESCRIPTION
**Pull request by midnightlynx**
dropped django 1.5/1.6 support, added 1.7/1.8 support, to match django's supported versions.
Added python 3.3/3.4 cross-compatibility through prudent use of six and python-modernize.

### CODE REVIEW

**Comment by midnightlynx** [comment]
Sorry, the ci settings need tweaked.

**Comment by midnightlynx** [comment]
I'm not entirely sure how to configure the .travis.yml to not try django 1.4 on python 3.x.

**Comment by midnightlynx** [comment]
Got it figured out.

**Comment by joestump** [comment]
Closing this in favor of #69, which is based off of this and bumps versions, etc.

**Pull request closed without merging**
